---
- name: snmp ro/rw string configuration
  hosts: switches
  gather_facts: no

  tasks:
    - name: ensure snmp strings are present
      ios_config:
        lines:
          - snmp-server community rocom RO
          - snmp-server community rwcom RW
