---
- name: snmp ro/rw string configuration
  hosts: switches
  gather_facts: no
  vars:
    readonlycom: rocom
    readwritecom: rwcom

  tasks:
    - name: ensure snmp strings are present
      ios_config:
        lines:
          - snmp-server community {{ readonlycom }} RO
          - snmp-server community {{ readonlycom }} RW
